### ISSUE TITLE
Maven support

### ISSUE THREAD

**Issue by RouHim** [lost-carrier/netatmo-api#1]
Hello,
is there a way to provide this library as maven dependency?
I would really love it.

Thank you && greetings
Rouven

**Comment by lost-carrier** [comment]
You mean available from Maven central? (I'm working on that...)

**Comment by RouHim** [comment]
Exactly, I forked your Projekt and did it by my own. 😇

**Comment by lost-carrier** [comment]
So - this project should now be available, too...

    <dependency>
        <groupId>org.losty.netatmo</groupId>
        <artifactId>netatmo-api</artifactId>
        <version>0.1.1</version>
    </dependency>

Cheers!
