### ISSUE TITLE
Client credentials grant type no longer supported

### ISSUE THREAD

**Issue by spooky1310** [lost-carrier/netatmo-api#12]
Netatmo has now finally disabled the client credentials grant type meaning login with username and password is no longer possible. https://dev.netatmo.com/apidocumentation/oauth#client-credential
However using their web form to login is not possible having a backend application fetching the data. It looks like that the refresh token never expires. So the approach would be to get the refresh token from e.g. https://dev.netatmo.com/apps/ and use it for "login" instead of username/password. Are you planning to fix your netatmo-api in this way?

BR
Dirk

**Comment by lost-carrier** [comment]
My collector stopped as well.

Have you tried that OAuthTokenStore
https://github.com/lost-carrier/netatmo-api/blob/aad9aa36bea9f08028d3bce7330aa3ef78ceede5/src/main/java/losty/netatmo/NetatmoHttpClient.java#L58 from @kaiwinter?

Did not have time to fix it my app, but that looks like it does use the access- and refreshTokens already...

**Comment by spooky1310** [comment]
Yes that works. Thanks for the hint.

**Comment by lost-carrier** [comment]
Didn't work for me, but should be fixed with 0.9.0 now.
