### ISSUE TITLE
Reuse OAuth token

### ISSUE THREAD

**Issue by kaiwinter** [lost-carrier/netatmo-api#8]
I'm working on my own [netatmo client](https://github.com/kaiwinter/myatmo-android) in which I'm using your library. Thank you for your effort, the library is perfectly simple I could get it running immediately.
The only thing I'm missing is the possibility to reuse the acquired OAuth token. I don't want to store the username/password in my client so I really want to use that token once I have it. I implemented this in my fork inspired by the [official netatmo sample](https://github.com/Netatmo/Netatmo-API-Android/tree/master/app/src/main/java/weatherstation/netatmo/com/netatmo_api_android/sample).
A new [constructor of NetatmoHttpClient](https://github.com/kaiwinter/netatmo-api/blob/master/src/main/java/losty/netatmo/NetatmoHttpClient.java#L67) can take a [TokenStore](https://github.com/kaiwinter/netatmo-api/blob/master/src/main/java/losty/netatmo/store/TokenStore.java) (interface) which can implement the persistence of the token. My fork contains a [PreferenceTokenStore](https://github.com/kaiwinter/netatmo-api/blob/master/src/main/java/losty/netatmo/store/PreferencesTokenStore.java) which saves the token by using the Java Preferences API. In my (android) client I'm using a SharedPreferencesTokenStore for example. 
This solution is fully backwards compatible. If no TokenStore is passed a TransientTokenStore is used which doesn't persist the token.

Oh and there was a method for refreshing the token in your code already. This is called now if the existing token is expired. Works as expected.

Please let me know what you think. In case you think this is useful I could open a pull request.

**Comment by lost-carrier** [comment]
Sorry for the delay.

Yes, PRs are always welcome.

Sounds good and also looks at a first glace. Just raise the PR and we'll check the details...
- backward compatibility would be important for me, but looks like that is already fine.
- maybe naming could be a bit clearer that this is about OAuth Tokens? 
- I guess you did check if there is anything pre-build from Oltu or something, right? (Sorry, I'm totally not an OAuth expert ;-) )

Thanks already in advance for the contribution!

...und viele Grüsse nach Kiel! ;-)

**Comment by kaiwinter** [comment]
I didn't know Oltu right now ;-) But I'm not doing anything with the OAuth protocol as everything was already there. I just implemented a persistence for the access token, refresh token and the expire date.
Everything gets restored from the TokenStore if NetatmoHttpClient is instantiated with one. The access token is used to identify a authorized user (instead of email/password). The access token has a lifetime of 3 hours (if I recall correct). The lifetime is determined by the expire date. If the access token is expired the refresh token is used to request a new access token from netatmo.

Your points one and three should be fine. What names to you have in mind for TokenStore (`OAuthTokenStore`?) and `PreferencesTokenStore` (`OAuthPreferencesTokenStore` or maybe just `PreferencesStore`) same question for `TransientTokenStore`.

... und natürlich Grüße zurück in die Schweiz :blush:

**Comment by lost-carrier** [comment]
Hmm... `PreferencesOAuthTokenStore` and `TransientOAuthTokenStore`?

...and the package? `oauthtoken` or `oauth.token` or even `oauth.token.store`? ...or just `oauth`?

**Comment by kaiwinter** [comment]
OK then I choose `oauthtoken `. Having one package only seems to be in line with the existing packages.

**Comment by lost-carrier** [comment]
Puh... solved 2 years ago... ;-)
